"""
Django settings for PbimsProject project.

Generated by 'django-admin startproject' using Django 1.10.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'mmc(r8#dq5rk86m1zq8%o%!g%f^!k#1mx^_!20o1vtli3&$+sq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
MEDIA_URL = '/'
MEDIA_ROOT = os.path.join(BASE_DIR)

ALLOWED_HOSTS = ['127.0.0.1', '0.0.0.0', '192.168.101.186', '192.168.100.61', '192.168.100.87', '116.68.205.72', 'www.mis.digital', 'mis.digital']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'PbimsApp'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'PbimsProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'PbimsProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default_old': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    },
    'default': {
                'NAME': 'PBIMS',
                'ENGINE': 'sqlserver_ado',
                'HOST': '192.168.100.61',
                'USER': 'sa',
                'PASSWORD': 'dataport',
                'OPTIONS': {
                            'provider': 'SQLOLEDB',
                            'use_legacy_date_fields': 'True'
                        }
            },
    'LogisticsEPSMirror': {
                'NAME': 'EPSNew',
                'ENGINE': 'sqlserver_ado',
                'HOST': '192.168.100.87',  #'HOST': '192.168.11.206', ## Use this ip, change user/pass accordingly to get data from EPSMirror when doing Churn Analytics
                'USER': 'sa',
                'PASSWORD': 'dataport',  #'PASSWORD': 'flexiload',
                'OPTIONS': {
                            'provider': 'SQLOLEDB',
                            'use_legacy_date_fields': 'True'
                        }
            }
}

#DATABASE_ROUTERS = ['PbimsApp.routers.DatabaseModelsRouter']

#DATABASE_MODELS_MAPPING = {
#    'PbimsApp': 'LogisticsEPSMirror',
#}

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

#For Generate the Log Please Add below code
# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': True,
#     'formatters': {
#         'standard': {
#             'format': '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
#         },
#     },
#     'handlers': {
#         'default': {
#             'level':'DEBUG',
#             'class':'logging.handlers.RotatingFileHandler',
#             'filename': 'logs/PbimsApp.log',
#             'maxBytes': 1024*1024*5, # 5 MB
#             'backupCount': 5,
#             'formatter':'standard',
#         },
#         'request_handler': {
#             'level':'DEBUG',
#             'class':'logging.handlers.RotatingFileHandler',
#             'filename': 'logs/PbimsProject.log',
#             'maxBytes': 1024*1024*5, # 5 MB
#             'backupCount': 5,
#             'formatter':'standard',
#         },
#     },
#     'loggers': {
#         '': {
#             'handlers': ['default'],
#             'level': 'DEBUG',
#             'propagate': True
#         },
#         'django.request': {
#             'handlers': ['request_handler'],
#             'level': 'DEBUG',
#             'propagate': True
#         },
#     }
# }

# LOGIN_URL='PbimsApp/login.html'
# LOGIN_REDIRECT_URL='PbimsApp/login.html'

# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'

EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'aciapprover111@gmail.com'
SERVER_EMAIL = 'Aciapprover111@gmail.com'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'Aciapprover111@gmail.com'
EMAIL_HOST_PASSWORD = '112358132134'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'